<?php
/**
 * Plugin's predefined constant
 */
class EventM_Constants {
	/**
	 * Status
	 *
	 * @var Status
	 */
	public static $status = array(
		'completed' => 'Completed',
		'cancelled' => 'Cancelled',
		'pending'   => 'Pending',
		'draft'     => 'Draft',
		'refunded'  => 'Refunded',
	);

	/**
	 * Offline Status
	 *
	 * @var Offline_Status
	 */
	public static $offline_status = array(
		'Pending'   => 'Pending',
		'Received'  => 'Received',
		'Cancelled' => 'Cancelled',
	);

	/**
	 * Currencies
	 *
	 * @var Currencies
	 */
	public static $currencies = array(
		'USD'  => 'United States Dollars',
		'EUR'  => 'Euros',
		'GBP'  => 'Pounds Sterling',
		'AED'  => 'United Arab Emirates dirham',
		'AFN'  => 'Afghan afghani',
		'ALL'  => 'Albanian lek',
		'AMD'  => 'Armenian dram',
		'AOA'  => 'Angolan kwanza',
		'ARS'  => 'Argentine peso',
		'AUD'  => 'Australian Dollars',
		'AZN'  => 'Azerbaijani manat',
		'BAM'  => 'Bosnia and Herzegovina convertible mark',
		'BBD'  => 'Barbadian dollar',
		'BDT'  => 'Bangladeshi taka',
		'BGN'  => 'Bulgarian lev',
		'BHD'  => 'Bahraini dinar',
		'BIF'  => 'Burundi Franc',
		'BND'  => 'Brunei dollar',
		'BOB'  => 'Bolivian boliviano',
		'BRL'  => 'Brazilian Real',
		'BSD'  => 'Bahamian dollar',
		'BTN'  => 'Bhutanese ngultrum',
		'BWP'  => 'Botswana pula',
		'BYN'  => 'Belarusian ruble',
		'BZD'  => 'Belize dollar',
		'CAD'  => 'Canadian Dollars',
		'CDF'  => 'Congolese franc',
		'CHF'  => 'Swiss Franc',
		'CLP'  => 'Chilean peso',
		'CNY'  => 'Chinese yuan',
		'COP'  => 'Colombian peso',
		'CRC'  => 'Costa Rican colón',
		'CUP'  => 'Cuban peso',
		'CVE'  => 'Cape Verdean escudo',
		'CZK'  => 'Czech Koruna',
		'DJF'  => 'Djiboutian franc',
		'DKK'  => 'Danish Krone',
		'DOP'  => 'Dominican peso',
		'DZD'  => 'Algerian dinar',
		'EGP'  => 'Egyptian pound',
		'ERN'  => 'Eritrean nakfa',
		'ETB'  => 'Ethiopian birr',
		'FJD'  => 'Fijian dollar',
		'GEL'  => 'Georgian lari',
		'GHS'  => 'Ghanaian cedi',
		'GMD'  => 'Gambian dalasi',
		'GNF'  => 'Guinean franc',
		'GTQ'  => 'Guatemalan quetzal',
		'HKD'  => 'Hong Kong Dollar',
		'HNL'  => 'Honduran lempira',
		'HRK'  => 'Croatian kuna',
		'HTG'  => 'Haitian gourde',
		'HUF'  => 'Hungarian Forint',
		'IDR'  => 'Indonesian rupiah',
		'ILS'  => 'Israeli Shekel',
		'INR'  => 'Indian Rupee',
		'IQD'  => 'Iraqi dinar',
		'IRR'  => 'Iranian rial',
		'ISK'  => 'Icelandic króna',
		'JMD'  => 'Jamaican dollar',
		'JOD'  => 'Jordanian dinar',
		'JPY'  => 'Japanese Yen',
		'KES'  => 'Kenyan shilling',
		'KGS'  => 'Kyrgyzstani som',
		'KHR'  => 'Cambodian riel',
		'KMF'  => 'Comorian franc',
		'KPW'  => 'North Korean won',
		'KRW'  => 'South Korean won',
		'KWD'  => 'Kuwaiti dinar',
		'KZT'  => 'Kazakhstani tenge',
		'LAK'  => 'Lao kip',
		'LBP'  => 'Lebanese pound',
		'LKR'  => 'Sri Lankan rupee',
		'LRD'  => 'Liberian dollar',
		'LSL'  => 'Lesotho loti',
		'LYD'  => 'Libyan dinar',
		'MAD'  => 'Moroccan dirham',
		'MDL'  => 'Moldovan leu',
		'MGA'  => 'Malagasy ariary',
		'MKD'  => 'Macedonian denar',
		'MMK'  => 'Burmese kyat',
		'MNT'  => 'Mongolian tögrög',
		'MRU'  => 'Mauritanian ouguiya',
		'MUR'  => 'Mauritian rupee',
		'MVR'  => 'Maldivian rufiyaa',
		'MWK'  => 'Malawian kwacha',
		'MXN'  => 'Mexican Peso',
		'MYR'  => 'Malaysian Ringgits',
		'MZN'  => 'Mozambican metical',
		'NAD'  => 'Namibian dollar',
		'NGN'  => 'Nigeria Naira',
		'NIO'  => 'Nicaraguan córdoba',
		'NOK'  => 'Norwegian Krone',
		'NPR'  => 'Nepalese rupee',
		'NZD'  => 'New Zealand Dollar',
		'OMR'  => 'Omani rial',
		'PAB'  => 'Panamanian balboa',
		'PEN'  => 'Peruvian sol',
		'PGK'  => 'Papua New Guinean kina',
		'PHP'  => 'Philippine Pesos',
		'PKR'  => 'Pakistani rupee',
		'PLN'  => 'Polish Zloty',
		'PYG'  => 'Paraguayan guaraní',
		'QAR'  => 'Qatari riyal',
		'RIAL' => 'Iranian Rial',
		'RON'  => 'Romanian leu',
		'RSD'  => 'Serbian dinar',
		'RUB'  => 'Russian Rubles',
		'RWF'  => 'Rwandan franc',
		'SAR'  => 'Saudi riyal',
		'SBD'  => 'Solomon Islands dollar',
		'SCR'  => 'Seychellois rupee',
		'SDG'  => 'Sudanese pound',
		'SEK'  => 'Swedish Krona',
		'SGD'  => 'Singapore Dollar',
		'SLL'  => 'Sierra Leonean leone',
		'SOS'  => 'Somali shilling',
		'SRD'  => 'Surinamese dollar',
		'SSP'  => 'South Sudanese pound',
		'STD'  => 'São Tomé and Príncipe dobra',
		'SYP'  => 'Syrian pound',
		'SZL'  => 'Swazi lilangeni',
		'THB'  => 'Thai Baht',
		'TJS'  => 'Tajikistani somoni',
		'TMT'  => 'Turkmenistan manat',
		'TND'  => 'Tunisian dinar',
		'TOP'  => 'Tongan pa\'anga',
		'TRY'  => 'Turkish Lira',
		'TTD'  => 'Trinidad and Tobago dollar',
		'TWD'  => 'Taiwan New Dollars',
		'TZS'  => 'Tanzanian shilling',
		'UAH'  => 'Ukrainian hryvnia',
		'UGX'  => 'Ugandan shilling',
		'UYU'  => 'Uruguayan peso',
		'UZS'  => 'Uzbekistani som',
		'VEF'  => 'Venezuelan bolívar',
		'VND'  => 'Vietnamese dong',
		'VUV'  => 'Vanuatu vatu',
		'WST'  => 'Samoan tala',
		'XAF'  => 'Central African CFA franc',
		'XCD'  => 'East Caribbean dollar',
		'XOF'  => 'West African CFA franc',
		'YER'  => 'Yemeni rial',
		'ZAR'  => 'South African Rand',
		'ZMW'  => 'Zambian kwacha',
	);

	/**
	 * Currency Symbol
	 *
	 * @var Currency_Symbol
	 */
	public static $currency_symbol = array(
		'USD'  => '$',
		'EUR'  => '€',
		'GBP'  => '£',
		'AED'  => 'AED',
		'AFN'  => 'AFN',
		'ALL'  => 'L',
		'AMD'  => '֏',
		'AOA'  => 'Kz',
		'ARS'  => '$',
		'AUD'  => '$',
		'AZN'  => 'AZN',
		'BAM'  => 'KM',
		'BBD'  => 'Bds$',
		'BDT'  => '৳',
		'BGN'  => 'Лв',
		'BHD'  => 'BD',
		'BIF'  => '₣',
		'BND'  => 'B$',
		'BOB'  => 'Bs',
		'BRL'  => 'R$',
		'BSD'  => 'B$',
		'BTN'  => 'Nu',
		'BWP'  => 'P',
		'BYN'  => 'BYN',
		'BZD'  => '$',
		'CAD'  => '$',
		'CDF'  => 'FC',
		'CHF'  => 'CHF',
		'CLP'  => '$',
		'CNY'  => '¥',
		'COP'  => '$',
		'CRC'  => '₡',
		'CUP'  => '₱',
		'CVE'  => '$',
		'CZK'  => 'Kč',
		'DJF'  => 'Fdj',
		'DKK'  => 'kr',
		'DOP'  => 'RD$',
		'DZD'  => 'DZD',
		'EGP'  => 'E£',
		'ERN'  => 'Nfk',
		'ETB'  => 'Br',
		'FJD'  => 'FJ$',
		'GEL'  => 'GEL',
		'GHS'  => 'GH₵',
		'GMD'  => 'D',
		'GNF'  => 'GFr',
		'GTQ'  => 'Q',
		'HKD'  => '$',
		'HNL'  => 'L',
		'HRK'  => 'kn',
		'HTG'  => 'G',
		'HUF'  => 'Ft',
		'IDR'  => 'Rp',
		'ILS'  => '₪',
		'INR'  => '₹',
		'IQD'  => 'IQD',
		'IRR'  => 'IRR',
		'ISK'  => 'kr',
		'JMD'  => '$',
		'JOD'  => 'JOD',
		'JPY'  => '¥',
		'KES'  => 'Ksh',
		'KGS'  => 'Лв',
		'KHR'  => '៛',
		'KMF'  => 'CF',
		'KPW'  => '₩',
		'KRW'  => '₩',
		'KWD'  => 'KD',
		'KZT'  => '₸',
		'LAK'  => '₭N',
		'LBP'  => 'LBP',
		'LKR'  => 'Rs',
		'LRD'  => 'L$',
		'LSL'  => 'L',
		'LYD'  => 'LD',
		'MAD'  => 'MAD',
		'MDL'  => 'L',
		'MGA'  => 'Ar',
		'MKD'  => 'Ден',
		'MMK'  => 'K',
		'MNT'  => '₮',
		'MRU'  => 'MRU',
		'MUR'  => '₨',
		'MVR'  => 'MVR',
		'MWK'  => 'MK',
		'MXN'  => '$',
		'MYR'  => 'RM',
		'MZN'  => 'MT',
		'NAD'  => 'N$',
		'NGN'  => '₦',
		'NIO'  => 'C$',
		'NOK'  => 'kr',
		'NPR'  => 'Rs',
		'NZD'  => '$',
		'OMR'  => 'OMR',
		'PAB'  => 'B/',
		'PEN'  => 'S/',
		'PGK'  => 'K',
		'PHP'  => '₱',
		'PKR'  => '₨',
		'PLN'  => 'zł',
		'PYG'  => '₲',
		'QAR'  => 'QR',
		'RIAL' => 'RIAL',
		'RON'  => 'lei',
		'RSD'  => 'din',
		'RUB'  => 'руб',
		'RWF'  => 'RF',
		'SAR'  => 'SR',
		'SBD'  => 'Si$',
		'SCR'  => 'SR',
		'SDG'  => 'SDG',
		'SEK'  => 'kr',
		'SGD'  => '$',
		'SLL'  => 'Le',
		'SOS'  => 'Sh.so.',
		'SRD'  => '$',
		'SSP'  => '£',
		'STD'  => 'Db',
		'SYP'  => '£S',
		'SZL'  => 'E',
		'THB'  => '฿',
		'TJS'  => 'ЅM',
		'TMT'  => 'T',
		'TND'  => 'DT',
		'TOP'  => 'T$',
		'TRY'  => 'TRY',
		'TTD'  => 'TT$',
		'TWD'  => 'NT$',
		'TZS'  => 'TSh',
		'UAH'  => '₴',
		'UGX'  => 'USh',
		'UYU'  => '$U',
		'UZS'  => 'so\'m',
		'VEF'  => 'Bs',
		'VND'  => '₫',
		'VUV'  => 'VT',
		'WST'  => 'WS$',
		'XAF'  => 'FCFA',
		'XCD'  => '$',
		'XOF'  => 'CFA',
		'YER'  => 'YER',
		'ZAR'  => 'R',
		'ZMW'  => 'ZK',
	);

	/**
	 * Calendar Locales
	 *
	 * @var Calendar_Locales
	 */
	public static $calendar_locales = array(
		'en',
		'af',
		'ar-dz',
		'ar-kw',
		'ar-ly',
		'ar-ma',
		'ar-sa',
		'ar-tn',
		'ar',
		'be',
		'bg',
		'bs',
		'ca',
		'cs',
		'da',
		'de-at',
		'de-ch',
		'de',
		'el',
		'en-au',
		'en-ca',
		'en-gb',
		'en-ie',
		'en-nz',
		'es-do',
		'es-us',
		'es',
		'et',
		'eu',
		'fa',
		'fi',
		'fr-ca',
		'fr-ch',
		'fr',
		'gl',
		'he',
		'hi',
		'hr',
		'hu',
		'id',
		'is',
		'it',
		'ja',
		'ka',
		'kk',
		'ko',
		'lb',
		'lt',
		'lv',
		'mk',
		'ms-my',
		'ms',
		'nb',
		'nl-be',
		'nl',
		'nn',
		'pl',
		'pt-br',
		'pt',
		'ro',
		'ru',
		'sk',
		'sl',
		'sq',
		'sr-cyrl',
		'sr',
		'sv',
		'th',
		'tr',
		'uk',
		'vi',
		'zh-cn',
		'zh-hk',
		'zh-tw',
	);

	/**
	 * Fonts
	 *
	 * @var Fonts
	 */
	private static $fonts = array( 'FreeSerif', 'Courier', 'Helvetica', 'Times' );

	/**
	 * Method for get currencies
	 */
	public static function get_currencies_cons() {
		return self::$currencies;
	}

	/**
	 * Method for get currency symbols
	 */
	public static function get_currency_symbol() {
		return self::$currency_symbol;
	}

	/**
	 * Method for get calendar locales
	 */
	public static function get_calendar_locales() {
		return self::$calendar_locales;
	}

	/**
	 * Method for get font
	 */
	public static function get_fonts_cons() {
		return self::$fonts;
	}
}
