<?php

class EventM_Global_Settings_Model extends EventM_Array_Model
{
    public $google_cal_client_id;
    public $google_cal_api_key;
    public $fb_api_key;
    public $gmap_api_key;
    public $registration_email_content;
    public $registration_email_subject;
    public $booking_pending_email;
    public $send_booking_confirm_email;
    public $send_admin_booking_confirm_email = 1;
    public $send_booking_cancellation_email;
    public $booking_confirmed_email;
    public $admin_booking_confirmed_email;
    public $booking_cancelation_email;
    public $booking_refund_email;
    public $reset_password_mail;
    public $event_submitted_email;
    public $event_approved_email;
    public $payment_confirmed_email;
    public $social_sharing;
    public $gcal_sharing;
    public $hide_past_events;
    public $performers_page;
    public $venues_page;
    public $events_page;
    public $booking_page;
    public $profile_page;
    public $event_submit_form;
    public $currency = 'USD';
    public $hide_expired_from_admin = 0;
    public $event_types;
    public $paypal_processor = 0;
    public $payment_test_mode = 0;
    public $paypal_email = '';
    public $paypal_api_username = '';
    public $paypal_api_password = '';
    public $paypal_api_sig = '';
    public $default_cal_view = 'month';
    public $disable_filter_options;
    public $hide_old_bookings;
    public $custom_css = '';
    public $time_format = 'h:mmt';
    public $ues_confirm_message = '';
    public $ues_login_message = '';
    public $ues_default_status = 'draft';
    public $enable_default_calendar_date = 0;
    public $default_calendar_date = '';
    public $disable_admin_email;
    public $disable_frontend_email;
    public $send_booking_pending_email;
    public $send_booking_refund_email;
    public $send_event_submitted_email;
    public $send_event_approved_email;
    public $frontend_submission_roles;
    public $ues_restricted_submission_message = '';
    public $show_no_of_events_card = 10;
    public $card_view_custom_value = 1;
    public $calendar_title_format = '';
    public $calendar_column_header_format = '';
    public $allow_submission_by_anonymous_user = '';
    public $shortcode_hide_upcoming_events = '';
    public $hide_calendar_rows = '';
    public $front_switch_view_option = array("month", "week", "day", "card", "list", "masonry", "slider");
    public $frontend_submission_sections = array('fes_event_featured_image' => 1, 'fes_event_booking' => 1, 'fes_event_link' => 1, 'fes_event_type' => 1, 'fes_event_location' => 1, 'fes_event_performer' => 1, 'fes_event_organizer' => 1, 'fes_event_more_options' => 1, 'fes_event_text_color' => 1);
    public $frontend_submission_required = array('fes_event_description' => 0, 'fes_event_booking' => 0, 'fes_booking_price' => 0,'fes_event_link' => 0, 'fes_event_type' => 0, 'fes_event_location' => 0, 'fes_event_performer' => 0, 'fes_event_organizer' => 0);
    public $required_booking_attendee_name = '';
    public $hide_0_price_from_frontend = '';
    public $datepicker_format = '';
    public $hide_event_custom_link = '';
    public $custom_booking_field_data = array();
    public $currency_position = 'before';
    public $show_qr_code_on_single_event = 0;
    public $show_qr_code_on_ticket = 0;
    public $booking_details_page;
    public $event_organizers;
    public $google_recaptcha;
    public $google_recaptcha_site_key;
    public $google_recaptcha_secret_key;
    public $button_titles;
    public $hide_time_on_front_calendar;
    public $enable_seo_urls;
    public $seo_urls;
    
    public $performer_display_view = 'card';
    public $performer_limit = 0;
    public $pop_performer_limit = 5;
    public $performer_no_of_columns = 4;
    public $performer_load_more = 1;
    public $performer_search = 1;
    public $single_performer_show_events = 1;
    public $single_performer_event_display_view = 'mini-list';
    public $single_performer_event_limit = 0;
    public $single_performer_event_column = 4;
    public $single_performer_event_load_more = 1;
    public $single_performer_hide_past_events = 1;
    public $performer_box_color = array('A6E7CF', 'DBEEC1', 'FFD3B6', 'FFA9A5');

    public $type_display_view = 'card';
    public $type_limit = 0;
    public $type_no_of_columns = 4;
    public $type_load_more = 1;
    public $type_search = 1;
    public $single_type_show_events = 1;
    public $single_type_event_display_view = 'mini-list';
    public $single_type_event_limit = 0;
    public $single_type_event_column = 4;
    public $single_type_event_load_more = 1;
    public $single_type_hide_past_events = 1;
    public $type_box_color = array('A6E7CF', 'DBEEC1', 'FFD3B6', 'FFA9A5');

    public $organizer_display_view = 'card';
    public $organizer_limit = 0;
    public $organizer_no_of_columns = 4;
    public $organizer_load_more = 1;
    public $organizer_search = 1;
    public $single_organizer_show_events = 1;
    public $single_organizer_event_display_view = 'mini-list';
    public $single_organizer_event_limit = 0;
    public $single_organizer_event_column = 4;
    public $single_organizer_event_load_more = 1;
    public $single_organizer_hide_past_events = 1;
    public $organizer_box_color = array('A6E7CF', 'DBEEC1', 'FFD3B6', 'FFA9A5');

    public $venue_display_view = 'card';
    public $venue_limit = 0;
    public $venue_no_of_columns = 4;
    public $venue_load_more = 1;
    public $venue_search = 0;
    public $single_venue_show_events = 1;
    public $single_venue_event_display_view = 'mini-list';
    public $single_venue_event_limit = 0;
    public $single_venue_event_column = 4;
    public $single_venue_event_load_more = 1;
    public $single_venue_hide_past_events = 1;
    public $venue_box_color = array('A6E7CF', 'DBEEC1', 'FFD3B6', 'FFA9A5');

    public $modern_paypal = 0;
    public $paypal_client_id;
    public $redirect_after_registration = 0;
}